#!/usr/bin/python3

# ============================================================
# zipf main program
#
# (C) Tiago Almeida 2016
#
# Still in early development stages.
#
# ============================================================
import argparse
import pprint
import sys
import modelparser as parser
import exceptions
import DjangoGenerator


def setup_cmdline_args():
	parser = argparse.ArgumentParser(
					description='Generate a web or mobile app')
	parser.add_argument('model_files', type=str, 
						nargs='+',
	                   	help='list of model files')
	parser.add_argument('--generator', dest='generator',
	                   	help='generator to be used')
	parser.add_argument('--list-generators', dest='accumulate', 
						action='store_const',
						const=1, default=0,
	                   	help='lists installed generators and exits')
	args = parser.parse_args()
	return args


def generate_app(models):
	generator = DjangoGenerator.DjangoGenerator(models)
	generator.go()


def main():
	args = setup_cmdline_args()
	model_files = args.model_files
	models = parser.parse_files(model_files)
	generate_app(models)
  	
if __name__ == '__main__':
  main()